#ifndef HEADER_H
#define HEADER_H
#include "route_struct.h"
#include <QDebug>
#include <QDate>
#include <QTime>
#include <QProcess>
#include <mpd/recv.h>
#include <mpd/client.h>
#include <mpd/status.h>
#include <mpd/entity.h>
#include <mpd/search.h>
#include <mpd/tag.h>
#include <mpd/message.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <QLineEdit>
#include <unistd.h>
#include <stdlib.h>
#include <QString>
#include <QThread>
#include <QRegExp>
#include <QByteArray>
#include <QStringListModel>
#include <QStringList>
#include <QListWidgetItem>
#include <QFont>
#include <QDebug>
#include <QBitArray>
#include <QPropertyAnimation>
#include <QLabel>
#include <QTimerEvent>
#include <QPushButton>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QRegion>
#include <QDir>
#include <QTimer>
#include <QProcess>
#include <QMessageBox>
#include <QPalette>
#include <QPropertyAnimation>
#include <QSpacerItem>
#include <QDesktopWidget>
#include <QPainter>
#include <QRect>
#include <QSqlTableModel>
#include <QSortFilterProxyModel>
#include <QtSql/QSqlDatabase>
#include <QtSql/QSqlQuery>
#include <QtSql/QSqlRecord>
#include <QtSql/QSqlTableModel>
#include <QStandardItemModel>
#include <QUdpSocket>
#include <QStandardPaths>
#include <QMutableLinkedListIterator>
#include <QGraphicsOpacityEffect>
#include "linphone/linphonecore.h"
#endif // HEADER_H

