#ifndef HEADER_H
#define HEADER_H
#include <QDebug>
#include <QProcess>
#include <mpd/recv.h>
#include <mpd/client.h>
#include <mpd/status.h>
#include <mpd/entity.h>
#include <mpd/search.h>
#include <mpd/tag.h>
#include <mpd/message.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <QString>
#include <QStringList>
#include <QFont>
#include <QDebug>
#include <QLabel>
#include <QTimerEvent>
#include <QRegion>
#include <QDir>
#include <QTimer>
#include <QProcess>
#include <QMessageBox>
#include <QPalette>
#include <QPainter>
#include <QRect>
#include <QSqlTableModel>
#include <QtSql/QSqlDatabase>
#include <QtSql/QSqlQuery>
#include <QtSql/QSqlRecord>
#include <QtSql/QSqlTableModel>
#endif // HEADER_H

