#############################################################################
# Makefile for building: mpd_api
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  qtmop.pro
# Template: app
# Command: /opt/Qt5.4.1/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile qtmop.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I/opt/Qt5.4.1/5.4/gcc_64/include -I/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets -I/opt/Qt5.4.1/5.4/gcc_64/include/QtGui -I/opt/Qt5.4.1/5.4/gcc_64/include/QtNetwork -I/opt/Qt5.4.1/5.4/gcc_64/include/QtSql -I/opt/Qt5.4.1/5.4/gcc_64/include/QtCore -I. -I. -I/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /opt/Qt5.4.1/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mpd_api1.0.0
DISTDIR = /home/apaul/streaming_project/qtmop/.tmp/mpd_api1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt5.4.1/5.4/gcc_64 -Wl,-rpath,/opt/Qt5.4.1/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -lmpdclient -L/opt/Qt5.4.1/5.4/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mpd.cpp \
		database.cpp \
		music_streamer.cpp \
		keyboard.cpp moc_mpd.cpp \
		moc_database.cpp \
		moc_music_streamer.cpp \
		moc_keyboard.cpp
OBJECTS       = main.o \
		mpd.o \
		database.o \
		music_streamer.o \
		keyboard.o \
		moc_mpd.o \
		moc_database.o \
		moc_music_streamer.o \
		moc_keyboard.o
DIST          = /opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/link_pkgconfig.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/lex.prf \
		qtmop.pro mpd.h \
		header.h \
		database.h \
		music_streamer.h \
		sql_enums.h \
		keyboard.h main.cpp \
		mpd.cpp \
		database.cpp \
		music_streamer.cpp \
		keyboard.cpp
QMAKE_TARGET  = mpd_api
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = mpd_api


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mpd.h ui_music_streamer.h ui_keyboard.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtmop.pro /opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/link_pkgconfig.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/uic.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/lex.prf \
		qtmop.pro \
		/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.prl \
		/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.prl \
		/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.prl \
		/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Network.prl \
		/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Sql.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile qtmop.pro
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/qconfig.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/link_pkgconfig.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/qt.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/resources.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/moc.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/uic.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt5.4.1/5.4/gcc_64/mkspecs/features/lex.prf:
qtmop.pro:
/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Widgets.prl:
/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Gui.prl:
/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Core.prl:
/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Network.prl:
/opt/Qt5.4.1/5.4/gcc_64/lib/libQt5Sql.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile qtmop.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mpd.h header.h database.h music_streamer.h sql_enums.h keyboard.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mpd.cpp database.cpp music_streamer.cpp keyboard.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mpd.ui music_streamer.ui keyboard.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mpd.cpp moc_database.cpp moc_music_streamer.cpp moc_keyboard.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mpd.cpp moc_database.cpp moc_music_streamer.cpp moc_keyboard.cpp
moc_mpd.cpp: /opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qicon.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		music_streamer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QWidget \
		database.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		sql_enums.h \
		mpd.h
	/opt/Qt5.4.1/5.4/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++ -I/home/apaul/streaming_project/qtmop -I/opt/Qt5.4.1/5.4/gcc_64/include -I/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets -I/opt/Qt5.4.1/5.4/gcc_64/include/QtGui -I/opt/Qt5.4.1/5.4/gcc_64/include/QtNetwork -I/opt/Qt5.4.1/5.4/gcc_64/include/QtSql -I/opt/Qt5.4.1/5.4/gcc_64/include/QtCore mpd.h -o moc_mpd.cpp

moc_database.cpp: /opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		sql_enums.h \
		database.h
	/opt/Qt5.4.1/5.4/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++ -I/home/apaul/streaming_project/qtmop -I/opt/Qt5.4.1/5.4/gcc_64/include -I/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets -I/opt/Qt5.4.1/5.4/gcc_64/include/QtGui -I/opt/Qt5.4.1/5.4/gcc_64/include/QtNetwork -I/opt/Qt5.4.1/5.4/gcc_64/include/QtSql -I/opt/Qt5.4.1/5.4/gcc_64/include/QtCore database.h -o moc_database.cpp

moc_music_streamer.cpp: /opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		database.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		sql_enums.h \
		music_streamer.h
	/opt/Qt5.4.1/5.4/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++ -I/home/apaul/streaming_project/qtmop -I/opt/Qt5.4.1/5.4/gcc_64/include -I/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets -I/opt/Qt5.4.1/5.4/gcc_64/include/QtGui -I/opt/Qt5.4.1/5.4/gcc_64/include/QtNetwork -I/opt/Qt5.4.1/5.4/gcc_64/include/QtSql -I/opt/Qt5.4.1/5.4/gcc_64/include/QtCore music_streamer.h -o moc_music_streamer.cpp

moc_keyboard.cpp: ui_keyboard.h \
		keyboard.h
	/opt/Qt5.4.1/5.4/gcc_64/bin/moc $(DEFINES) -I/opt/Qt5.4.1/5.4/gcc_64/mkspecs/linux-g++ -I/home/apaul/streaming_project/qtmop -I/opt/Qt5.4.1/5.4/gcc_64/include -I/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets -I/opt/Qt5.4.1/5.4/gcc_64/include/QtGui -I/opt/Qt5.4.1/5.4/gcc_64/include/QtNetwork -I/opt/Qt5.4.1/5.4/gcc_64/include/QtSql -I/opt/Qt5.4.1/5.4/gcc_64/include/QtCore keyboard.h -o moc_keyboard.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mpd.h ui_music_streamer.h ui_keyboard.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mpd.h ui_music_streamer.h ui_keyboard.h
ui_mpd.h: mpd.ui
	/opt/Qt5.4.1/5.4/gcc_64/bin/uic mpd.ui -o ui_mpd.h

ui_music_streamer.h: music_streamer.ui
	/opt/Qt5.4.1/5.4/gcc_64/bin/uic music_streamer.ui -o ui_music_streamer.h

ui_keyboard.h: keyboard.ui
	/opt/Qt5.4.1/5.4/gcc_64/bin/uic keyboard.ui -o ui_keyboard.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mpd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qicon.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		music_streamer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QWidget \
		database.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		sql_enums.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QApplication \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qapplication.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qeventloop.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qguiapplication.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mpd.o: mpd.cpp mpd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QMainWindow \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qicon.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		music_streamer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QWidget \
		database.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		sql_enums.h \
		ui_mpd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpd.o mpd.cpp

database.o: database.cpp database.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		sql_enums.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o database.o database.cpp

music_streamer.o: music_streamer.cpp music_streamer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QWidget \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qwidget.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobal.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qconfig.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfeatures.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtypetraits.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsysinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlogging.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qflags.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmutex.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnumeric.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qnamespace.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstring.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qchar.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrefcount.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qarraydata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qalgorithms.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiterator.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcoreevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmetatype.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qisenum.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qobject_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmargins.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qrect.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsize.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpoint.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpalette.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcolor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qrgb.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringlist.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdatastream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qiodevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qpair.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qregexp.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qbrush.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvector.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qmatrix.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpolygon.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qregion.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qline.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtransform.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainterpath.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qimage.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixelformat.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpixmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qshareddata.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qhash.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfont.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qfontinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qcursor.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qkeysequence.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qevent.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qvariant.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qmap.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdebug.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtextstream.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qlocale.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qset.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurl.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qurlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfile.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfiledevice.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qvector2d.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		header.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDebug \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QProcess \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qprocess.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QString \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QStringList \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QFont \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/QLabel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qlabel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtWidgets/qframe.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimerEvent \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QRegion \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QDir \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qdir.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qfileinfo.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QTimer \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qtimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qbasictimer.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPalette \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/QPainter \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpainter.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qtextoption.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtGui/qpen.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlDatabase \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqldatabase.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsql.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlQuery \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquery.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlRecord \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlrecord.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/QSqlTableModel \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqltablemodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtSql/qsqlquerymodel.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		database.h \
		/opt/Qt5.4.1/5.4/gcc_64/include/QtCore/QObject \
		sql_enums.h \
		ui_music_streamer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o music_streamer.o music_streamer.cpp

keyboard.o: keyboard.cpp keyboard.h \
		ui_keyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o keyboard.cpp

moc_mpd.o: moc_mpd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpd.o moc_mpd.cpp

moc_database.o: moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_database.o moc_database.cpp

moc_music_streamer.o: moc_music_streamer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_music_streamer.o moc_music_streamer.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

